<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-9JB0BLCJ" failures="2" tests="5" name="Test" time="7.783" errors="0" timestamp="2025-05-18T12:20:21 CDT">
  <testcase classname="api.test.UserTests" name="testPostUser" time="3.523"/>
  <testcase classname="api.test.UserTests" name="testGetUserByusername" time="0.699"/>
  <testcase classname="api.test.UserTests" name="testupdateUserByusername" time="1.023"/>
  <testcase classname="api.test.UserTests" name="testdeleteUserByusername" time="0.669">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testdeleteUserByusername(UserTests.java:91)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testdeleteUserByusername -->
  <testcase classname="api.test.UserTests" name="testPostUserWithArray" time="0.445">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at api.test.UserTests.testPostUserWithArray(UserTests.java:107)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testPostUserWithArray -->
</testsuite> <!-- Test -->
